### ISSUE TITLE
Missing Property Data

### ISSUE THREAD

**Issue by F-Kaufmann** [FOSSEE/OMChemSim#23]
Hello,

I'm trying to simulate an air liquefaction process using OMChemSim. During some preliminary tests I realized there is no Joule-Thomson effect observable when performing an isenthalpic expansion of the components "Air" or a mixture of "Nitrogen" and "Oxygen". (The expansion was performed using two material streams and the "valve" unit operation)

Since the effect can be observed using different components from the property databank, I assume my issue arises from missing property data for the before mentioned components. When I looked up the property data for "Air", "Nitrogen" and "Oxygen" I realized there are several parameters that have the value 0 assigned to them. To fix my issue I want to look up the corresponding property data but I can't figure out what the abbreviations in the "General_Properties" model stand for.

In explicit I'm looking for the meanig of the abbreviations "DM", "SH", "IGHF" and "GEF". If there is some general documentation for the abbreviations in the "General_Properties" model I would be very thankful for a hint on where to find it.

Thank you in advance and kind regards

**Comment by nayakpriyam** [comment]
Here are the abbreviations:

DM: Dipole Moment
SH: Absolute Enthalpy
IGHF: Heat of Formation
GEF: Gibbs Energy of Formation

We are in the process of adding documentation for the complete Simulator package and this might take some time. However, general documentation for the abbreviations in the "General_Properties" will be made available in the next release.

**Comment by F-Kaufmann** [comment]
Thanks for the answer! I was checking some of the property values and another question popped up:
In which form is the Absolute Enthalpy implemented in your model? i.e. what is the used unit and what is the used reference point?

Thanks and best regards

**Comment by nayakpriyam** [comment]
Units for Absolute Enthalpy is J/kmol and is calculated as the difference between Heat of Formation and Standard Heat of Vaporization at 298.15 K.

**Comment by nayakpriyam** [comment]
Current master has been updated with the units and description of general properties and therefore the issue is closed.
