### ISSUE TITLE
Taking input for variable Base Component twice while simulating PFR

### ISSUE THREAD

**Issue by nayakpriyam** [FOSSEE/OMChemSim#37]
While simulating the PFR example, It is noticed that the user has to give input for variable Base Component twice (once for Base_C and again for BC_r[Nr]).

The variable which is used to define "Base Component" in a reaction is defined twice: once in the kinetic reaction model (BC_r[Nr]) and once in the PFR model (Base_C). Also, the variable is declared once as an array(BC_r[Nr]) and again as an integer(Base_C). Since both these variables are used in the code, therefore they cannot be removed arbitrarily.

This leads to taking input from the user twice in two different forms for the same variable, which represents the base component. This conflict needs to be addressed. 

![image](https://user-images.githubusercontent.com/34299789/70603946-acfb4880-1c1d-11ea-8ba3-ea5855517fb8.png)

**Comment by RahulNagraj444** [comment]
Addressed through PR#40
